const SOS_CONTENT = {
  key: "default",
  contacts: [
    {
      id: "tourism",
      accent: "#f97316",
      category: "Tourism assistance",
      department: "Sri Lanka Tourism Hotline",
      summary: "Best first contact for tourist safety concerns, scams, harassment, and licensed travel-service complaints.",
      primaryNumber: "1912",
      primaryHref: "tel:1912",
      secondaryNumber: "+94 11 2426800",
      secondaryHref: "tel:+94112426800",
      websiteHref: "https://www.sltda.gov.lk/en/contact-us",
      websiteLabel: "SLTDA Contact Page",
      bullets: [
        "Tourist harassment or scam complaints",
        "Urgent visitor support and local coordination",
        "Non-medical help while travelling",
      ],
      availability: "Tourism hotline",
      source: "Official SLTDA hotline and contact page",
    },
    {
      id: "ambulance",
      accent: "#ef4444",
      category: "Medical emergency",
      department: "1990 Suwa Seriya Ambulance Service",
      summary: "For accidents, chest pain, injuries, or any urgent medical situation requiring an ambulance.",
      primaryNumber: "1990",
      primaryHref: "tel:1990",
      websiteHref: "https://www.1990suwaseriya.lk/",
      websiteLabel: "1990 Suwa Seriya",
      bullets: [
        "Emergency ambulance dispatch",
        "Fastest option for medical transport",
        "Use when someone needs urgent treatment",
      ],
      availability: "Emergency ambulance line",
      source: "Official ambulance service and SLTDA tourist portal",
    },
    {
      id: "police",
      accent: "#3b82f6",
      category: "Police assistance",
      department: "Sri Lanka Police Headquarters",
      summary: "Use this when you need police support for theft, assault, traffic accidents, unsafe situations, or formal reports.",
      primaryNumber: "+94 11 2421111",
      primaryHref: "tel:+94112421111",
      secondaryNumber: "+94 11 2440584",
      secondaryHref: "tel:+94112440584",
      websiteHref: "https://www.police.lk/",
      websiteLabel: "Sri Lanka Police",
      bullets: [
        "Theft, violence, and accidents",
        "Police reports for insurance or embassy use",
        "Escalation when personal safety is at risk",
      ],
      availability: "Police headquarters",
      source: "Official Sri Lanka Police contact page",
    },
    {
      id: "immigration",
      accent: "#22c55e",
      category: "Passport and visa help",
      department: "Department of Immigration and Emigration",
      summary: "Best for visa extension help, passport-related guidance, and immigration support while you are in Sri Lanka.",
      primaryNumber: "1962",
      primaryHref: "tel:1962",
      secondaryNumber: "+94 11 2101500",
      secondaryHref: "tel:+94112101500",
      email: "controller@immigration.gov.lk",
      emailHref: "mailto:controller@immigration.gov.lk",
      websiteHref: "https://www.immigration.gov.lk/index_e.php?page=contact",
      websiteLabel: "Immigration Contact Page",
      bullets: [
        "Lost passport follow-up and immigration guidance",
        "Tourist visa or departure issues",
        "Official department email for document inquiries",
      ],
      availability: "Department hotline and main office",
      source: "Official Department of Immigration and Emigration contact page",
    },
    {
      id: "dmc",
      accent: "#a855f7",
      category: "Weather and disaster response",
      department: "Disaster Management Centre",
      summary: "For floods, landslides, cyclones, severe weather alerts, and wider disaster-response coordination.",
      primaryNumber: "117",
      primaryHref: "tel:117",
      secondaryNumber: "+94 11 2136222",
      secondaryHref: "tel:+94112136222",
      websiteHref: "https://www.dmc.gov.lk/",
      websiteLabel: "Disaster Management Centre",
      bullets: [
        "Flood, storm, or landslide emergencies",
        "Emergency operations updates",
        "Official weather and disaster notices",
      ],
      availability: "Call center and emergency operations",
      source: "Official Disaster Management Centre call center details",
    },
  ],
  scenarios: [
    {
      title: "Medical emergencies",
      primary: "Call 1990 Suwa Seriya first",
      body: "Use the ambulance line for injuries, sudden illness, breathing issues, or when someone cannot travel safely without medical support.",
    },
    {
      title: "Accidents, theft, or feeling unsafe",
      primary: "Call Sri Lanka Police",
      body: "Use the police contacts for crime reports, road accidents, personal safety concerns, and official documentation after an incident.",
    },
    {
      title: "Lost passport or visa trouble",
      primary: "Call Immigration, then your embassy",
      body: "The immigration department can guide you on visa status, travel documents, and the next steps needed before departure.",
    },
    {
      title: "Harassment, scams, or tourism complaints",
      primary: "Call the Tourism Hotline 1912",
      body: "Use the tourism hotline when the issue involves visitors, licensed tourism services, or situations where you need tourist-specific guidance.",
    },
    {
      title: "Natural disasters or severe weather",
      primary: "Call the Disaster Management Centre",
      body: "If heavy rain, flooding, landslides, storms, or evacuations affect your route, the DMC is the right escalation point.",
    },
  ],
  reasons: [
    "Medical emergencies",
    "Accidents",
    "Lost passports",
    "Harassment or scams",
    "Natural disasters or severe weather",
  ],
  prepSteps: [
    "Share your exact location, hotel name, nearest landmark, and callback number first.",
    "Say clearly whether the issue is medical, police-related, passport-related, or weather-related.",
    "Keep a passport copy, booking details, and travel insurance details ready if you have them.",
    "After urgent calls, contact your hotel, guide, or embassy if more support is needed.",
  ],
  sources: [
    {
      label: "Sri Lanka Tourism Development Authority",
      detail: "1912 tourism hotline and +94 11 2426800 contact line",
      href: "https://www.sltda.gov.lk/en/contact-us",
    },
    {
      label: "Sri Lanka Police",
      detail: "+94 11 2421111 and +94 11 2440584",
      href: "https://www.police.lk/",
    },
    {
      label: "Department of Immigration and Emigration",
      detail: "1962, +94 11 2101500, controller@immigration.gov.lk",
      href: "https://www.immigration.gov.lk/index_e.php?page=contact",
    },
    {
      label: "Disaster Management Centre",
      detail: "117 call center and +94 11 2136222 emergency operations",
      href: "https://www.dmc.gov.lk/",
    },
    {
      label: "1990 Suwa Seriya",
      detail: "Official ambulance contact and service site",
      href: "https://www.1990suwaseriya.lk/",
    },
  ],
};

module.exports = { SOS_CONTENT };